[touch-gestures]
description = "Touch gestures"
version = "0.0.1"
author = "horriblename"

[split-monitor-workspaces.build]
output = "touch-gestures.so"
steps = [
    "mkdir -p build",
    "cmake -B build",
    "cmake --build build",
]
