[hyprgrass]
description = "Touch gestures"
version = "0.6.0"
author = "horriblename"

[hyprgrass.build]
output = "build/src/libhyprgrass.so"
steps = [
    "meson setup build",
    "ninja -C build",
]
