[touch-gestures]
description = "Touch gestures"
version = "0.0.1"
author = "horriblename"

[touch-gestures.build]
output = "_build/libtouch-gestures.so"
steps = [
    "meson setup _build",
    "ninja -C _build",
]
